# Generated by Django 3.1a1 on 2020-06-05 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djstripe', '0006_2_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationfee',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='applicationfeerefund',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='balancetransaction',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='card',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='charge',
            name='on_behalf_of',
            field=models.ForeignKey(help_text='The account the charge was made on behalf of. Null here indicates that this value was never set.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='on_behalf_of_charges', to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='countryspec',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='customer',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='event',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='event',
            name='pending_webhooks',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of webhooks that have yet to be successfully delivered (i.e., to return a 20x response) to the URLs you’ve specified.'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='payout',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='plan',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='product',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='refund',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='scheduledqueryrun',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='session',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='setupintent',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='source',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='transferreversal',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='upcominginvoice',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='account',
            field=models.ForeignKey(help_text="The connected account (if any) in which the object was made. Null here indicates that the object belongs to the platform's account.", null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.account'),
        ),
        migrations.AddField(
            model_name='webhookeventtrigger',
            name='endpoint_type',
            field=djstripe.fields.StripeEnumField(default='account', enum=djstripe.enums.EndpointType, help_text='The endpoint type that this event was triggered from.', max_length=7),
        ),
        migrations.AlterField(
            model_name='charge',
            name='account',
            field=models.ForeignKey(help_text='The account the charge was made on. Null here indicates that this value was never set. (Previously this field was described as on_behalf_of)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='djstripe.account'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='on_behalf_of',
            field=models.ForeignKey(blank=True, help_text='The account (if any) for which the funds of the PaymentIntent are intended.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='on_behalf_of_paymentintents', to='djstripe.account'),
        ),
        migrations.AlterField(
            model_name='setupintent',
            name='on_behalf_of',
            field=models.ForeignKey(blank=True, help_text='The account (if any) for which the setup is intended.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='on_behalf_of_setupintents', to='djstripe.account'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('subscriber', 'livemode', 'account')},
        ),
    ]
