# Generated by Django 3.1a1 on 2020-06-12 18:58

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0007_auto_20200605_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='capabilities',
            field=djstripe.fields.JSONField(blank=True, help_text='A hash containing the set of capabilities that was requested for this account and their associated states. Keys are names of capabilities. Values may be active, inactive, or pending.', null=True),
        ),
    ]
