# Generated by Django 2.2 on 2022-05-20 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0008_account_capabilities'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
    ]
