# Generated by Django 2.2.16 on 2025-05-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0010_auto_20240711_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='applicationfee',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='applicationfeerefund',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='balancetransaction',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='default_for_currency',
            field=models.BooleanField(blank=True, help_text='Whether this external account is the default account for its currency.', null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='charge',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='auto_advance',
            field=models.BooleanField(blank=True, help_text='Controls whether Stripe will perform automatic collection of the invoice. When false, the invoice’s state will not automatically advance without an explicit action.', null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='payout',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(blank=True, help_text='Whether the product is currently available for purchase. Only applicable to products of `type=good`.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shippable',
            field=models.BooleanField(blank=True, help_text='Whether this product is a shipped good. Only applicable to products of `type=good`.', null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='scheduledqueryrun',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='setupintent',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='transferreversal',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='upcominginvoice',
            name='auto_advance',
            field=models.BooleanField(blank=True, help_text='Controls whether Stripe will perform automatic collection of the invoice. When false, the invoice’s state will not automatically advance without an explicit action.', null=True),
        ),
        migrations.AlterField(
            model_name='upcominginvoice',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
        migrations.AlterField(
            model_name='usagerecord',
            name='livemode',
            field=models.BooleanField(blank=True, default=None, help_text='Null here indicates that the livemode status is unknown or was previously unrecorded. Otherwise, this field indicates whether this record comes from Stripe test mode or live mode operation.', null=True),
        ),
    ]
