# Generated by Django 2.2.16 on 2025-11-06 16:41

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0012_alter_invoice_charge_alter_invoice_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='us_bank_account',
            field=djstripe.fields.JSONField(blank=True, help_text='If this is a us_bank_account PaymentMethod, this hash contains details about the bank account.', null=True),
        ),
    ]
