# Generated by Django 2.2.16 on 2025-11-17 18:45

from django.db import migrations
import djstripe.enums
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0013_paymentmethod_us_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='business_type',
            field=djstripe.fields.StripeEnumField(blank=True, default='', enum=djstripe.enums.BusinessType, help_text='The business type.', max_length=11),
        ),
    ]
