# Generated by Django 2.2.16 on 2026-01-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0014_auto_20251117_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='api_version',
            field=models.CharField(blank=True, help_text='the API version at which the event data was rendered. Blank for old entries only, all new entries will have this value', max_length=64),
        ),
    ]
